version: "3.7"
services:
    nginx:
      image: nginx:alpine
      ports:
      - target: 80
        published: 80
        protocol: tcp
      volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      deploy:
        replicas: 1

    frontend:
      image: vlin303/frontendimage:latest
      build: ./frontend
      deploy:
        replicas: 2
      ports:
      - target: 5000
        published: 5000
        protocol: tcp
      depends_on:
      - "classgen"
      - "namegen"
      - "healthgen"

    classgen:
      image: vlin303/classgenimage:latest      
      build: ./classgen
      deploy:
        replicas: 2
      ports:
      - target: 5001
        protocol: tcp

    namegen:
      image: vlin303/namegenimage:latest      
      build: ./namegen
      deploy:
        replicas: 2
      ports:
      - target: 5002
        protocol: tcp

    healthgen:
      image: vlin303/healthgenimage:latest      
      build: ./healthgen
      deploy:
        replicas: 2
      ports:
      - target: 5003
        protocol: tcp
    