version: "3.7"
services:
  nginx:
    image: nginx:alpine
    deploy:
      replicas: 2
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - "frontend"
  frontend:
    image: vlin303/frontendimage:latest
    build: ./frontend
    deploy:
      replicas: 2
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
    - "classgen"
    - "namegen"
    - "healthgen"
  classgen:
    image: vlin303/classgenimage:latest      
    build: ./classgen
    deploy:
      replicas: 2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
    - DB_URI=${DB_URI}
    - KEY=${KEY}
  namegen:
    image: vlin303/namegenimage:latest      
    build: ./namegen
    deploy:
      replicas: 2
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    environment:
    - DB_URI=${DB_URI}
    - KEY=${KEY}
  healthgen:
    image: vlin303/healthgenimage:latest      
    build: ./healthgen
    deploy:
      replicas: 2
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
