- name: "Check if Swarm has already been Initialized"
  community.general.docker_swarm:
    state: present

- name: "Get swarm info"
  community.general.docker_swarm_info:
  register: swarm_info

- name: "Get a join token"
  add_host:
    name: "token"
    value: "{{ swarm_info['swarm_facts']['JoinTokens']['Worker'] }}"